# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-protoc-adpotopenjdk-hs:
    name: Compile Protobuf Check (AdoptiumJDK-HS)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest Adoptium LTS releases, and latest non-LTS version supported by gradle
        java: [ 8, 11, 14 ]
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest Adoptium JDK ${{ matrix.java }} (hotspot) built for linux
        run: curl -L "https://api.adoptopenjdk.net/v3/binary/latest/${{ matrix.java }}/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk" -o aojdk${{ matrix.java }}-hs.tar.gz
      - name: Setup Latest Adoptium JDK (hotspot) ${{ matrix.java }}
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
          jdkFile: ./aojdk${{ matrix.java }}-hs.tar.gz
      - name: Print java version
        run: java -version
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-gradle
      - name: Build and test with Gradle
        run: ./gradlew clean build

